### ISSUE TITLE
Class EcomDev\ProductDataPreLoader\DataService\ProductAdapterFactory does not exist

### ISSUE THREAD

**Issue by MageCloudTeam** [EcomDev/magento2-product-preloader#2]
Incorrect class name:
`EcomDev\ProductDataPreLoader\DataService\ProductAdapterFactory`
In class:
`EcomDev\ProductDataPreLoader\Observer\ListCollectionAfterLoad`
Need to replace with:
`EcomDev\ProductDataPreLoader\DataService\MagentoProductWrapperFactory`

**Comment by IvanChepurnyi** [comment]
Check `road-to-1.0` it is fixed there already long time ago.
